[package]
name = "fileup"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
clap = {version = "4.5.20", features = ["derive", "env"]}
dotenv = "0.15.0"
env_logger = "0.11.5"
futures = "0.3.31"
lazy_static = "1.5.0"
log = "0.4.22"
